// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'PLACEHOLDER_API_KEY',
    appId: '1:1234567890:web:1234567890',
    messagingSenderId: '1234567890',
    projectId: 'quiz-app-travel-placeholder',
    authDomain: 'quiz-app-travel-placeholder.firebaseapp.com',
    storageBucket: 'quiz-app-travel-placeholder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxV_bJP22oeObmg9E7zq3gxjaM3MsaXG0',
    appId: '1:58793994198:android:ed695851253034c8332677',
    messagingSenderId: '58793994198',
    projectId: 'quizapptravel',
    storageBucket: 'quizapptravel.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQxr-vKIr3a54nU6ChGC7e6jPAjXt1CC8',
    appId: '1:58793994198:ios:aad8b149fffe682c332677',
    messagingSenderId: '58793994198',
    projectId: 'quizapptravel',
    storageBucket: 'quizapptravel.firebasestorage.app',
    iosBundleId: 'com.example.quizAppTravel',
  );
}
